# Generated by Django 4.1.6 on 2023-03-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="resdential_address",
            new_name="residential_address",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
