# Generated by Django 4.1.6 on 2023-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_rename_resdential_address_customuser_residential_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mobile_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
